# Generated by Django 3.0.3 on 2020-02-26 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Djeday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu', models.TextField()),
                ('ans', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Planet')),
                ('question', models.ManyToManyField(to='DjedaysAcademy.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Djeday')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Planet')),
            ],
            managers=[
                ('with_padawans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Question')),
            ],
            options={
                'unique_together': {('candidate', 'question')},
            },
        ),
    ]
