# Generated by Django 3.0.3 on 2020-02-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjedaysAcademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jedi',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
