# Generated by Django 3.0.3 on 2020-02-26 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('DjedaysAcademy', '0002_auto_20200227_0157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jedi',
            managers=[
                ('with_padawans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Jedi'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DjedaysAcademy.Question'),
        ),
    ]
