# Generated by Django 3.0.3 on 2020-02-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjedaysAcademy', '0005_auto_20200227_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.BooleanField(null=True),
        ),
    ]
